docs/source/usrman/intro.rst
=> changed "not" to "no"

mpi.cfg, src/lib-mpi/compat/openmpi.h
=> Update mpi.cfg for Fujitsu MPI

src/mpi4py/futures/_lib.py
=> mpi4py.futures: Fix sys.path[0] on workers if using `-m` flag

docs/source/usrman/tutorial.rst
Added two examples for One-Sided communication.
=> docs: One-Sided communication example

.github/workflows/ci.yml, demo/futures/test_futures.py, test/test_cco_ngh_buf.py, test/test_cco_ngh_obj.py, test/test_datatype.py, test/test_mpimem.py, test/test_p2p_buf_matched.py, test/test_p2p_obj_matched.py, test/test_pack.py, test/test_util_dtlib.py
Related MPICH pull requests:
* pmodels/mpich#5163
* pmodels/mpich#5167
* pmodels/mpich#5168
* pmodels/mpich#5193
Related Open MPI pull requests:
* open-mpi/ompi#8735
* open-mpi/ompi#8769
* open-mpi/ompi#8779
* open-mpi/ompi#8908
* open-mpi/ompi#8941
=> test: Update testsuite to run with MPICH and Open MPI development

demo/cuda-aware-mpi/use_cupy.py, demo/cuda-aware-mpi/use_numba.py, docs/source/usrman/tutorial.rst
=> Update doc and demo for GPU arrays

docs/source/usrman/envvars.rst, docs/source/usrman/toctree.txt
Close #31.
Question: Does any of the CI test doc builds? It's easier for me to just inspect the post-build artifact...
=> Add docs for env vars

CHANGES.rst, docs/source/usrman/overview.rst, docs/source/usrman/tutorial.rst, src/mpi4py/MPI/asbuffer.pxi, src/mpi4py/MPI/ascaibuf.pxi, src/mpi4py/MPI/asdlpack.pxi, src/mpi4py/MPI/msgbuffer.pxi, src/msvcfix.h, test/arrayimpl.py, test/dlpackimpl.py, test/mpiunittest.py, test/test_msgspec.py
=> Add support for DLPack

CHANGES.rst, DESCRIPTION.rst, docs/index.rst, docs/mpi4py.bib, docs/source/usrman/citing.rst
I just checked and it is still in the Early Access phase, so we don't have a full reference number yet, but the DOI alone is already citable.
=> [DOC] Add new paper

.pylintrc, conf/mpidistutils.py, conf/mypy.stubtest.allow.txt, src/mpi4py/util/dtlib.py, src/mpi4py/util/pkl5.pyi
See pypa/setuptools#2963
Fixes #157
=> setup: Fixes after changes in setuptools 60.x

test/test_errhandler.py
=> test: Refactor Errhandler tests

test/main.py, test/test_dynproc.py
**DO-NOT-MERGE**: This PR will be merged manually
=> [WIP] update/test

src/lib-mpi/compat/mpich.h, src/lib-mpi/config/mpi-40.h
* [MPI-4.0 errata document](https://www.mpi-forum.org/docs/mpi-4.0/errata-40.pdf)
* Issue mpi-forum/mpi-issues#517
* mpi-forum/mpi-standard#620
* Issue pmodels/mpich#5413
* pmodels/mpich#6146
=> MPI-4: Handle MPI_Status_set_elements_c from MPI-4.0 errata

test/test_rma.py, test/test_rma_nb.py
More comprehensive alternative to #295
=> test: Use context manager to manage locking in RMA tests

conf/mpidistutils.py
=> build: Fix editable installs (mpi.cfg file)

docs/source/conf.py
Workarounds: When using the option, `__init__`/`__new__` are injected into `special-members`, then into `members`, and finally rendered at the end of `autoclass`. Therefore, patch `ClassDocumenter`'s `__init__` to remove the forcibly injected members.
=> docs: Use Sphinx autodoc_class_signature='separate'

.github/workflows/dist.yml, .gitignore, MANIFEST.in, conf/docutils.conf, docs/source/.gitignore, docs/source/apidoc.py, src/mpi4py/MPI/Comm.pyx, src/mpi4py/MPI/Datatype.pyx, src/mpi4py/MPI/Errhandler.pyx, src/mpi4py/MPI/ErrorCode.pyx, src/mpi4py/MPI/Exception.pyx, src/mpi4py/MPI/File.pyx, src/mpi4py/MPI/Group.pyx, src/mpi4py/MPI/Info.pyx, src/mpi4py/MPI/MPI.pyx, src/mpi4py/MPI/Message.pyx, src/mpi4py/MPI/Op.pyx, src/mpi4py/MPI/Request.pyx, src/mpi4py/MPI/Session.pyx, src/mpi4py/MPI/Status.pyx, src/mpi4py/MPI/Win.pyx, src/mpi4py/MPI/asbuffer.pxi, src/mpi4py/MPI/atimport.pxi, src/mpi4py/MPI/commimpl.pxi, src/mpi4py/MPI/msgbuffer.pxi, src/mpi4py/MPI/msgpickle.pxi, src/mpi4py/MPI/typedec.pxi, src/mpi4py/MPI/typestr.pxi, test/test_doc.py, tox.ini
* Do not include documentation in source distribution.
* Reformat and fix mpi4py.MPI one-line docstrings.
=> Documentation

INSTALL.rst, README.rst, conf/mpidistutils.py
Fixes #407.
cc: @YarShev @leofang
=> Minor improvements install instructions and documentation

src/mpi4py/MPI/asarray.pxi, src/mpi4py/MPI/msgbuffer.pxi, src/mpi4py/MPI/msgpickle.pxi, test/test_msgspec.py
=> bugfix: Rework is_integral check to handle NumPy arrays

.azure/install-openmpi.sh, .circleci/env.sh, .codespellrc, .github/workflows/ci-cover.yml, CHANGES.rst, src/mpi4py/typing.py, src/mpi4py/typing.pyi, test/test_spawn.py
=> type: Fix SupportsBuffer definition to support Python < 3.12

.appveyor.yml, demo/futures/test_futures.py, src/lib-mpi/compat/mpich.h, test/test_dynproc.py, test/test_spawn.py, test/test_util_pool.py
https://github.com/pmodels/mpich/pull/5467
https://github.com/pmodels/mpich/pull/6835
https://github.com/pmodels/mpich/pull/6822
https://github.com/pmodels/mpich/pull/6816
=> Update after MPICH 4.3 CH4:UCX support for dynamic processes

.github/workflows/ci-build.yml, .github/workflows/ci-cover.yml, .github/workflows/ci-test.yml, .github/workflows/dist.yml
=> build(deps): bump actions/(upload|download)-artifact from 3 to 4

demo/check-mpiexec/run.sh, src/mpi4py/MPI/atimport.pxi
* Allow for runtime MPI vendor detection.
* Add support for Intel MPI.
=> refactor: Rework mpiexec mismatch checks

src/lib-mpi/compat/mpich.h, test/test_errhandler.py, test/test_fortran.py
cf. https://github.com/mpi4py/mpi4py/issues/418#issuecomment-2026805886
=> test: Additional testing for Python <-> Fortran handle conversion

src/mpi4py/MPI.src/ascaibuf.pxi, src/mpi4py/MPI.src/asdlpack.pxi, test/dlpackimpl.py, test/test_msgspec.py
* [dlpack](https://dmlc.github.io/dlpack/latest/python_spec.html#python-spec)
* [array-apis](https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__dlpack__.html#array_api.array.__dlpack__)
=> dlpack: Update to DLPack v1.0 and Python array API v2023.12

test/main.py
In case there is a significant number of exclude patterns, it would be more convenient to supply them in a line-separated file. I have implemented this feature here.
=> Add --xfile option to provide an exclude pattern file

.flake8, docs/source/intro.rst, src/mpi4py/futures/aplus.py, src/mpi4py/futures/pool.py, src/mpi4py/util/pkl5.py, src/mpi4py/util/pool.py, src/mpi4py/util/sync.py
=> Linting and documentation fixes

test/dlpackimpl.py
cc @leofang @mhpierre 
Fixes #596.
=> test: Fix bug in ctypes DLPack implementation

.appveyor.yml, .azure/steps.yml, .github/workflows/ci-build.yml, src/mpi4py/run.py, test/coverage.sh
=> feat: Add command line option --mpi-library to mpi4py.run

src/mpi4py/MPI.src/ascaibuf.pxi, src/mpi4py/MPI.src/asdlpack.pxi, test/arrayimpl.py, test/dlpackimpl.py, test/test_msgspec.py
Follow up of #611, cf #609.
cc @seberg @snsunx-nv
=> dlpack: Pass capsule around to hold ownership on the managed tensor

conf/mpiapigen.py, mpi.cfg, src/lib-mpi/config.h, src/lib-mpi/config/mpi-50.h, src/lib-mpi/config/mpiabi.h, src/lib-mpi/missing.h
cf. mpi-forum/mpi-abi-stubs#39
=> Update support for MPI ABI

conf/mpiapigen.py, docs/source/conf.py, src/lib-mpi/largecnt.h, src/lib-mpi/mpiapi40.h, src/mpi4py/util/pkl5.py, test/test_datatype.py
https://doi.org/10.1109/ExaMPI.2014.5
=> feat: Use BigMPI's contiguous datatype as large-count fallback

.github/workflows/ci-build.yml, src/_mpi_dll_path.py
* Support loading the release or debug DLL via `I_MPI_LIBRARY_KIND`
=> feat: Intel MPI Python DLL search path on Windows

src/mpi4py/futures/pool.py
=> futures: avoid exceeding `buffersize` tasks in `map`

src/lib-mpi/config/openmpi.h
open-mpi/ompi#13342
cc @hppritcha
=> build: Support MPI_ERR_ERRHANDLER under Open MPI

test/test_datatype.py
=> test: Handle know failures on Debian
