docs/source/usrman/mpi4py.futures.rst

This PR updates documentation on how to run scripts with dynamically spawned processes for Open MPI implementation as well as adds an example with using MPI4PY_MAX_WORKERS env variable.
It is based on the discussion https://github.com/open-mpi/ompi/issues/8171

docs: Update examples on scripts execution

---

docs/source/usrman/mpi4py.futures.rst
docs/source/usrman/tutorial.rst

Hi! I was reading the documentation to familiarize myself with mpi4py. This PR fixes a couple small errors - a missing space that caused Sphinx rendering problems, and a typo. Thank you for your work on mpi4py, it is a very helpful tool!

[DOC] Fix typos.

---

test/test_rma.py

In this pull request, I fixed a violation of the MPI standard in the way MPI_Compare_and_swap and MPI_Fetch_and_op are called in test_rma.py.
I fixed it like a pull request and it now passes, but I feel like it's weird to fix the disp, so do you know the right way to do it?
I think it is essential that the alignment of the send and receive buffers match the alignment of the data types.
In MPI-3.1, 3.3.1 Type Matching Rule, it says
```
Type matching has to be observed at each of these three phases: 
The type of each variable in the sender buffer has to match the type specified for that entry by the send operation; 
the type specified by the send operation has to match the type specified by the receive operation; 
and the type of each variable in the receive buffer has to match the type …
```

test: Alignment of send/receive buffers and data types in test_rma

---

test/arrayimpl.py
test/test_cco_buf.py
test/test_cco_nb_buf.py
test/test_cco_ngh_buf.py
test/test_p2p_buf.py
test/test_spawn.py

Work in progress. 
This PR aims to fix the known test errors when there are more than 1 processes. Now multi-process tests can run fine on the same GPU (verified up to`mpirun -n 4`). A typical symptom of such errors is random outcomes, which happen because the input arrays are not yet fully ready before MPI accesses their buffers via CUDA Array Interface.

Fix GPU tests for size>=2

---

src/mpi4py/util/dtlib.py
test/test_util_dtlib.py
tox.ini

Do not assume alignment, use NumPy or ctypes to determine struct slot offsets.
Closes #91.

mpi4py.util.dtlib: Fix alignment

---

docs/source/usrman/mpi4py.futures.rst

The documentation discusses how `COMM_WORLD` is split when using the `-m mpi4py.futures` command line feature but says that it will create "16 workers". If my understanding is correct, when you run with N processes, it will create N-1 workers. I've updated the documentation to reflect this.

docs: clarify communicator split when using -m mpi4py.futures

---

src/mpi4py/MPI/asbuffer.pxi
src/mpi4py/MPI/ascaibuf.pxi
src/mpi4py/MPI/msgbuffer.pxi
test/test_msgspec.py

Handle byte order markers at the beginning of format strings

---

test/test_rma.py

test: Fix bad RMA tests by adding sync before memory deallocation

---

test/test_dynproc.py

Don't assume IPv4 sockets are available in TestDPM.testJoin
(test_dynproc.py). Instead, use the family reported available by
socket.getaddrinfo().
Use INET (IPv4) by default if available, otherwise INET6 (IPv6) or
UNIX sockets. An undocumented socket family will also be used if no
other is available.
Intended to enable testJoin to pass on IPv6-only networks.
Fixes #240.

allow IPv6 sockets in test_dynproc.py testJoin

---

docs/source/overview.rst

Hi!
I found a small typo in the docs and corrected it. 
Thanks,
Andrei

Fix small typo in overview article in docs

---

.github/workflows/ci.yml
MANIFEST.in
conf/intelmpi.pth
conf/mpiconfig.py
conf/mpidistutils.py
setup.py
src/mpi4py/CMakeLists.txt

Since Python 3.8, Windows DLLs are no longer searched in the `PATH` environment variable. While I understand the rationale behind this change, they should have introduced a new environment variable, let say `PYTHONDLLPATH`, to easily add to the search path. Otherwise, the only way is to use `os.add_dll_directory()` programatically.
Intel MPI does not install DLLs in system locations but the `I_MPI_ROOT` install tree. Moreover, the package installs two DLLs, one for debug and another for release. Users typically pick the one they want by running `setvars.bat`, and that batch script simply modifies `PATH`. But Python no longer uses `PATH` for DLL search. So here we are.
A quick and dirty workaround is to install a *.pth file in site-packages that will first look for `I_MPI_ROOT` defined in …

build: Intel MPI and Python DLL search path on Windows

---

.github/workflows/ci-build.yml
conf/builder.py
conf/mpiapigen.py
conf/pyproject-meson.toml
conf/requirements-build-mesonpy.txt
setup.py
test/arrayimpl.py
tox.ini

* Simplify handling of alternative backend names
* Add support for `MPI4PY_BUILD_BACKEND=meson-python`
* Add Tox envs to test {pip|build} with {scikit-build|meson-python}

build: Simplify and enhance support for multiple build backends

---

CHANGES.rst
CMakeLists.txt
meson.build
setup.py
src/mpi4py/futures/_base.pyi
src/mpi4py/futures/_core.py
src/mpi4py/futures/aplus.py
src/mpi4py/typing.pyi
test/test_package.py

Python 3.7 is too old (and EOLed) and proper testing of typing stubs in CI would require workarounds to silence errors.

type: Do not install stubs for Python 3.7 or older

---

.azure/pipelines.yml
conf/ci/appveyor-artifacts.py
src/mpi4py/run.py
test/coverage.sh

* `python -m mpi4py --prefix` will tell users where the thing is installed. This way users can quickly figure out if they are importing mpi4py from the wrong location.
* `python -m mpi4py --mpi-std-version` to have an idea of the minimum MPI feature set available.
* `python -m mpi4py --mpi-lib-version` to get info on the backend implementation via `MPI_Get_library_version()`.

mpi4py.run: Add convenience command line options

---

.gitignore
CHANGES.rst
CMakeLists.txt
conf/mpiconfig.py
conf/mpidistutils.py
docs/source/mpi4py.rst
makefile
meson.build
setup.cfg
src/mpi4py/__init__.py

From next release, `mpi4py.get_config()` will return an empty dictionary. However, third-party packagers and distributors can still add an `mpi.cfg` file as package data to provide users with MPI  build information (compiler wrappers, includes, libraries).

refactor: mpi4py.get_config() now returns an empty dictionary

---

src/mpi4py/MPI/asbuffer.pxi

Fixes #450.
cc @alexfanqi @negril

fix: Fix implementation of MPI.buffer.toreadonly()

---

demo/futures/test_futures.py
test/test_dynproc.py
test/test_spawn.py
test/test_util_pool.py

As a side effect of disabling spawn tests, this also disables testing for the mpi4py.futures and mpi4py.util.pool modules.
* Setenv `MPI4PY_TEST_SPAWN=1` to enable spawn tests.
* Setenv `MPI4PY_TEST_DYNPROC=1` to enable dynproc tests.

test: Disable spawn and dynproc tests by default under Open MPI v5.x

---

src/mpi.pth

After semantic changes to `locals()` in Python  3.13, successive lines of `*.pth` files do not preserve values of local variables defined in various lines (starting with `import`). An easy, albeit unaesthetic, fix is to join all these lines with `;` in a single executable line.
https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-locals-semantics

fix: Update `mpi.pth` after changes in Python 3.13

---

demo/init-fini/test_6.py
test/test_cco_ngh_obj.py
test/test_cco_obj.py
test/test_cco_obj_inter.py
test/test_p2p_obj.py
test/test_p2p_obj_matched.py
test/test_util_pkl5.py
test/test_util_pool.py

Refactor Python 2 code to use Python 3 constructs. Notable is the use of `{}` for dicts and sets.
Used [pyupgrade](https://github.com/asottile/pyupgrade) 3.17.0 with `--py3-plus`.

pyupgrade: Refactor Python 2 code to Python 3 constructs.

---

.github/workflows/ci-abi.yml
docs/source/conf.py

`obj` needs to be passed as the second argument, not the first one.
Fixes #668.
With this change, I can get the Debian package build successfully with both Sphinx 8.1 and 8.2.

docs: Fix get_documenter monkey-patching for Sphinx 8.1
